### PR TITLE
Chapter36 fixes

### PR DESCRIPTION
**Pull request by vojta7**
Code in other chapters seems to be ok.

### CODE REVIEW

**Comment by vojta7** [comment]
I did also stumbled across "TODO: text!" at the end of section "Updating Wave Function Collapse" in chapter 36, so I wanted to mention it, in case you forgot.

**Comment by vojta7** [comment]
Prefab builder was causing entities duplication, it can be seen in current wasm build.

**Comment by thebracket** [comment]
I've fixed up the TODO - thank you! I believe this PR fixes issue #63 . Testing it locally. Thank you so much for all the work!

**Comment by vojta7** [comment]
Yes, this should fix it.

You are welcome, I really like your tutorial, so I am trying to put some work back. In other chapters, It is not always that easy, because I am using legion instead of specs.

**Comment by thebracket** [comment]
I've wished a few times that I'd started with Legion, but it barely existed when I started. I've played around with it, and it is a really amazing ECS.

**Comment by oubiwann** [comment]
Oh, wow ... just read through the Legion code and benchmarks. I'm thinking about still following along in the tutorial, but switching over to it ...

**Pull request merged**
